This notebook contains proof of accuration of my model,we will apply predictions on training and testing datasets and see how accurate is our model.We will also see how to apply our model on images taken by rasberrypi.


In [ ]:
from tensorflow.compat.v1 import ConfigProto
from tensorflow.compat.v1 import InteractiveSession

config = ConfigProto()
config.gpu_options.per_process_gpu_memory_fraction = 0.5
config.gpu_options.allow_growth = True
session = InteractiveSession(config=config)

In [ ]:
from tensorflow.keras.layers import Input, Lambda, Dense, Flatten
from tensorflow.keras.models import Model
from tensorflow.keras.applications.inception_v3 import InceptionV3
#from keras.applications.vgg16 import VGG16
from tensorflow.keras.applications.inception_v3 import preprocess_input
from tensorflow.keras.preprocessing import image
from tensorflow.keras.preprocessing.image import ImageDataGenerator,load_img
from tensorflow.keras.models import Sequential
import numpy as np
from glob import glob
#import matplotlib.pyplot as plt

In [ ]:
from tensorflow.keras.models import load_model
from tensorflow.keras.preprocessing import image
model=load_model('model_ofintrn.h5')
#model=load_model('model_ofintrn11.h5')

In [ ]:
import os
from tensorflow.keras.preprocessing import image
from tensorflow.keras.preprocessing.image import ImageDataGenerator
am=0
test_okimagespath='/content/drive/MyDrive/intrnship/casting_data/casting_data/test/ok_front'
test_defimagespath='/content/drive/MyDrive/intrnship/casting_data/casting_data/test/def_front'
train_okimagespath='/content/drive/MyDrive/intrnship/casting_data/casting_data/train/ok_front'
train_defimagespath='/content/drive/MyDrive/intrnship/casting_data/casting_data/train/def_front'
    
vb=0 
for i in os.listdir(test_defimagespath):     
      #print(im)
      am=am+1
      if am<60:
   
        imgpath=os.path.join(test_defimagespath,i)
        img=image.load_img(imgpath,target_size=(250,250))#load any image here
        x=image.img_to_array(img)
        
        #x=x/255
        
        import numpy as np
        x=np.expand_dims(x,axis=0)
        img_data=preprocess_input(x)
        img_data.shape
        a=model.predict(img_data)
        print(a)
        print(i)
        
        for im in a:
          bn=0
          for ing in im:
            bn=bn+1
            if bn%2==0:    
             if ing>0.001:
               print("ok_front")
               vb=vb+1
print(f"{vb} ok images are present")
               #print(ing)

[[9.9999988e-01 1.9443859e-10]]
cast_def_0_1553.jpeg
[[9.9902904e-01 6.6723869e-06]]
cast_def_0_1666.jpeg
[[1.000000e+00 7.431259e-15]]
cast_def_0_1613.jpeg
[[9.9999416e-01 3.7356807e-07]]
cast_def_0_1233.jpeg
[[0.42537355 0.01475572]]
cast_def_0_2273.jpeg
ok_front
[[1.000000e+00 1.582104e-11]]
cast_def_0_1359.jpeg
[[9.9999964e-01 1.9183281e-07]]
cast_def_0_1153.jpeg
[[0.9999622  0.00170933]]
cast_def_0_1570.jpeg
ok_front
[[1.0000000e+00 2.8317127e-12]]
cast_def_0_2104.jpeg
[[1.0000000e+00 1.1849181e-08]]
cast_def_0_1492.jpeg
[[9.994066e-01 2.557239e-05]]
cast_def_0_2274.jpeg
[[9.999739e-01 5.614450e-04]]
cast_def_0_1505.jpeg
[[1.000000e+00 2.962973e-15]]
cast_def_0_2276.jpeg
[[1.0000000e+00 3.3342992e-21]]
cast_def_0_2247.jpeg
[[1.0000000e+00 2.6376283e-13]]
cast_def_0_138.jpeg
[[9.9999976e-01 7.0546797e-08]]
cast_def_0_2100.jpeg
[[9.9985909e-01 2.4912695e-06]]
cast_def_0_149.jpeg
[[1.0000000e+00 5.0182566e-23]]
cast_def_0_1211.jpeg
[[0.9583042  0.00292576]]
cast_def_0_1471.jpeg
ok_fr

We have done prediction on 60 defective images of testing dataset.We got 5 ok images means our accuracy is 91.66% in this case.

In [ ]:
am=0
vb=0 
for i in os.listdir(test_okimagespath):     
      #print(im)
      am=am+1
      if am<60:
   
        imgpath=os.path.join(test_okimagespath,i)
        img=image.load_img(imgpath,target_size=(250,250))#load any image here
        x=image.img_to_array(img)
        
        #x=x/255
        
        import numpy as np
        x=np.expand_dims(x,axis=0)
        img_data=preprocess_input(x)
        img_data.shape
        a=model.predict(img_data)
        print(a)
        print(i)
        
        for im in a:
          bn=0
          for ing in im:
            bn=bn+1
            if bn%2==0:    
             if ing>0.001:
               print("ok_front")
               vb=vb+1
print(f"{vb} ok images are present")
               #print(ing)

[[1.6916871e-06 9.9994254e-01]]
cast_ok_0_7631.jpeg
ok_front
[[1.2284292e-07 9.9998188e-01]]
cast_ok_0_2724.jpeg
ok_front
[[1.0440899e-05 9.9324775e-01]]
cast_ok_0_2926.jpeg
ok_front
[[7.4147823e-07 9.9989080e-01]]
cast_ok_0_3294.jpeg
ok_front
[[5.8653055e-11 1.0000000e+00]]
cast_ok_0_952.jpeg
ok_front
[[0.925579   0.27431658]]
cast_ok_0_31.jpeg
ok_front
[[3.9763792e-05 9.9997926e-01]]
cast_ok_0_2850.jpeg
ok_front
[[1.4926549e-08 9.9998319e-01]]
cast_ok_0_998.jpeg
ok_front
[[1.4868186e-05 9.9903905e-01]]
cast_ok_0_505.jpeg
ok_front
[[6.5850976e-08 9.9998164e-01]]
cast_ok_0_2892.jpeg
ok_front
[[5.2079446e-10 9.9999988e-01]]
cast_ok_0_4475.jpeg
ok_front
[[1.6908220e-05 9.9654335e-01]]
cast_ok_0_880.jpeg
ok_front
[[0.20920524 0.9974986 ]]
cast_ok_0_4992.jpeg
ok_front
[[8.712868e-07 9.999758e-01]]
cast_ok_0_5809.jpeg
ok_front
[[1.5862128e-08 9.9999762e-01]]
cast_ok_0_2894.jpeg
ok_front
[[1.6978222e-04 9.9119788e-01]]
cast_ok_0_1144.jpeg
ok_front
[[0.17955482 0.9784742 ]]
cast_ok_0_2732.jpe

We have done prediction on 60 non-defective(ok) images of testing dataset.We got 59 ok images means our accuracy is 98.33% in this case

In [ ]:
am=0
vb=0 
for i in os.listdir(train_okimagespath):     
      #print(im)
      am=am+1
      if am<60:
   
        imgpath=os.path.join(train_okimagespath,i)
        img=image.load_img(imgpath,target_size=(250,250))#load any image here
        x=image.img_to_array(img)
        
        #x=x/255
        
        import numpy as np
        x=np.expand_dims(x,axis=0)
        img_data=preprocess_input(x)
        img_data.shape
        a=model.predict(img_data)
        print(a)
        print(i)
        
        for im in a:
          bn=0
          for ing in im:
            bn=bn+1
            if bn%2==0:    
             if ing>0.001:
               print("ok_front")
               vb=vb+1
print(f"{vb} ok images are present")
               #print(ing)


[[1.9803033e-12 1.0000000e+00]]
cast_ok_0_5141.jpeg
ok_front
[[3.1842292e-06 9.5900428e-01]]
cast_ok_0_594.jpeg
ok_front
[[5.6636225e-08 9.9997866e-01]]
cast_ok_0_5815.jpeg
ok_front
[[1.12501994e-13 1.00000000e+00]]
cast_ok_0_6169.jpeg
ok_front
[[1.5832256e-09 9.9999380e-01]]
cast_ok_0_4967.jpeg
ok_front
[[1.2561366e-11 1.0000000e+00]]
cast_ok_0_8412.jpeg
ok_front
[[9.095906e-08 9.999956e-01]]
cast_ok_0_5263.jpeg
ok_front
[[1.9394237e-09 9.9999988e-01]]
cast_ok_0_7228.jpeg
ok_front
[[6.7210774e-04 9.9871707e-01]]
cast_ok_0_8863.jpeg
ok_front
[[6.2402696e-09 9.9998677e-01]]
cast_ok_0_6994.jpeg
ok_front
[[7.950552e-09 9.999993e-01]]
cast_ok_0_7437.jpeg
ok_front
[[1.1176824e-06 9.9957377e-01]]
cast_ok_0_5021.jpeg
ok_front
[[4.3488501e-07 9.9997354e-01]]
cast_ok_0_9543.jpeg
ok_front
[[7.344754e-11 9.999999e-01]]
cast_ok_0_5645.jpeg
ok_front
[[2.9739342e-04 9.9999022e-01]]
cast_ok_0_6814.jpeg
ok_front
[[8.7313424e-07 9.9685657e-01]]
cast_ok_0_8517.jpeg
ok_front
[[3.4536484e-08 9.9999285e-01

We have done prediction on 60 non-defective(ok) images of training dataset.We got 59 ok images means our accuracy is 98.33% in this case


In [ ]:
     
am=0
vb=0 
for i in os.listdir(train_defimagespath):     
      #print(im)
      am=am+1
      if am<60:
   
        imgpath=os.path.join(train_defimagespath,i)
        img=image.load_img(imgpath,target_size=(250,250))#load any image here
        x=image.img_to_array(img)
        
        #x=x/255
        
        import numpy as np
        x=np.expand_dims(x,axis=0)
        img_data=preprocess_input(x)
        img_data.shape
        a=model.predict(img_data)
        print(a)
        print(i)
        
        for im in a:
          bn=0
          for ing in im:
            bn=bn+1
            if bn%2==0:    
             if ing>0.001:
               print("ok_front")
               vb=vb+1
print(f"{vb} ok images are present")
               #print(ing)

[[1.0000000e+00 2.8398234e-10]]
cast_def_0_985.jpeg
[[9.978999e-01 3.210355e-05]]
cast_def_0_9065.jpeg
[[0.35785037 0.03667231]]
cast_def_0_9169.jpeg
ok_front
[[9.9999189e-01 3.6432812e-07]]
cast_def_0_913.jpeg
[[0.98542345 0.00139462]]
cast_def_0_8740.jpeg
ok_front
[[9.795908e-01 7.662599e-05]]
cast_def_0_8762.jpeg
[[1.0000000e+00 1.6003657e-11]]
cast_def_0_8786.jpeg
[[1.000000e+00 6.290925e-10]]
cast_def_0_9355.jpeg
[[1.0000000e+00 1.4794071e-08]]
cast_def_0_9500.jpeg
[[9.9999845e-01 1.2615348e-10]]
cast_def_0_8768.jpeg
[[1.0000000e+00 4.5697523e-22]]
cast_def_0_9157.jpeg
[[0.94939214 0.00364957]]
cast_def_0_8979.jpeg
ok_front
[[1.0000000e+00 6.8768116e-09]]
cast_def_0_9379.jpeg
[[1.000000e+00 7.464226e-20]]
cast_def_0_91.jpeg
[[1.0000000e+00 2.3152513e-10]]
cast_def_0_933.jpeg
[[9.9999845e-01 9.5992597e-08]]
cast_def_0_9495.jpeg
[[9.9945730e-01 1.8934082e-04]]
cast_def_0_8644.jpeg
[[0.15902737 0.94538224]]
cast_def_0_8532.jpeg
ok_front
[[9.999976e-01 4.189996e-10]]
cast_def_0_8621.j

We have done prediction on 60 defective images of training dataset.We got 6 ok images means our accuracy is 90.66% in this case.


To apply model on rasberrypi,you just store image in imagepath variable ,you will get result.


In [ ]:
imgpath='/content/cast_ok_0_9.jpeg'#store images comming from rasberrypi camera here
img=image.load_img(imgpath,target_size=(250,250))#load any image here
x=image.img_to_array(img)

#x=x/255

import numpy as np
x=np.expand_dims(x,axis=0)
img_data=preprocess_input(x)
img_data.shape
a=model.predict(img_data)
#print(a)
#print(i)

for im in a:
  bn=0
  for ing in im:
    bn=bn+1
    if bn%2==0:    
      if ing>0.001:
        print("ok_front")
      else:
       print("defective")

ok_front


In [ ]:
imgpath='/content/cast_def_0_2.jpeg'
img=image.load_img(imgpath,target_size=(250,250))#load any image here
x=image.img_to_array(img)

#x=x/255

import numpy as np
x=np.expand_dims(x,axis=0)
img_data=preprocess_input(x)
img_data.shape
a=model.predict(img_data)
#print(a)
#print(i)

for im in a:
  bn=0
  for ing in im:
    bn=bn+1
    if bn%2==0:    
      if ing>0.001:
        print("ok_front")
      else:
       print("defective")

defective
